name: Deploy to staging
on:
  push:
    branches: [ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      
      - name: Executing remote ssh command
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 34.47.137.234
          username: ayushFirstInstance
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ci-cd-class
            git pull origin main
            export PATH=/root/.nvm/versions/node/v22.13.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
            npm install -g pnpm
            pnpm install
            pnpm run build
            pm2 restart 0 1 2
            echo "Deployed successfully"